# -*- coding: utf-8 -*-
"""task 1  .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hETjKKiecqGy_jD34l4XXbNfrE7Z_epl
"""

#Task.....1 (Kabirul_Islam_Supplier_and_Shipment_Management_System)
import pandas as pd
import sqlite3
from datetime import datetime

# Load the CSV file
file_name = "SPM.csv"
data = pd.read_csv(file_name)

# Connect to SQLite database
conn = sqlite3.connect('supplier_shipment_management.db')
cursor = conn.cursor()

# Create Suppliers table
cursor.execute('''
CREATE TABLE IF NOT EXISTS Suppliers (
    SupplierID TEXT PRIMARY KEY,
    SupplierName TEXT NOT NULL,
    ContactPerson TEXT,
    ContactNumber TEXT,
    Address TEXT
)
''')

# Create Shipments table
cursor.execute('''
CREATE TABLE IF NOT EXISTS Shipments (
    ShipmentID TEXT PRIMARY KEY,
    SupplierID TEXT,
    ItemID TEXT,
    ItemName TEXT,
    Quantity INTEGER,
    ShipmentDate DATE,
    DeliveryDate DATE,
    ShipmentStatus TEXT,
    FOREIGN KEY (SupplierID) REFERENCES Suppliers(SupplierID)
)
''')

# Populate tables from CSV
for _, row in data.iterrows():
    cursor.execute('''
    INSERT OR IGNORE INTO Suppliers (SupplierID, SupplierName, ContactPerson, ContactNumber, Address)
    VALUES (?, ?, ?, ?, ?)
    ''', (row['Supplier ID'], row['Supplier Name'], row['Contact Person'], row['Contact Number'], row['Address']))

    cursor.execute('''
    INSERT OR IGNORE INTO Shipments (ShipmentID, SupplierID, ItemID, ItemName, Quantity, ShipmentDate, DeliveryDate, ShipmentStatus)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    ''', (row['Shipment ID'], row['Supplier ID'], row['Item ID'], row['Item Name'], row['Quantity'], row['Shipment Date'], row['Delivery Date'], row['Shipment Status']))

conn.commit()

# Task 1: Supplier Management
def supplier_management():
    while True:
        print("\nSupplier Management:")
        print("1. Add New Supplier")
        print("2. Update Supplier Details")
        print("3. List Suppliers Providing Specific Items")
        print("4. Back to Main Menu")
        choice = input("Enter your choice: ")

        if choice == '1':
            supplier_id = input("Supplier ID: ")
            supplier_name = input("Supplier Name: ")
            contact_person = input("Contact Person: ")
            contact_number = input("Contact Number: ")
            address = input("Address: ")
            cursor.execute('''
            INSERT OR IGNORE INTO Suppliers (SupplierID, SupplierName, ContactPerson, ContactNumber, Address)
            VALUES (?, ?, ?, ?, ?)
            ''', (supplier_id, supplier_name, contact_person, contact_number, address))
            conn.commit()
            print("Supplier added successfully.")
        elif choice == '2':
            supplier_id = input("Supplier ID: ")
            field = input("Field to update (SupplierName, ContactPerson, ContactNumber, Address): ")
            new_value = input("New Value: ")
            cursor.execute(f'''
            UPDATE Suppliers SET {field} = ? WHERE SupplierID = ?
            ''', (new_value, supplier_id))
            conn.commit()
            print("Supplier updated successfully.")
        elif choice == '3':
            item_id = input("Item ID: ")
            cursor.execute('''
            SELECT DISTINCT Suppliers.SupplierName
            FROM Suppliers
            JOIN Shipments ON Suppliers.SupplierID = Shipments.SupplierID
            WHERE Shipments.ItemID = ?
            ''', (item_id,))
            suppliers = cursor.fetchall()
            print("Suppliers providing the specified item:")
            for supplier in suppliers:
                print(supplier[0])
        elif choice == '4':
            break
        else:
            print("Invalid choice. Please try again.")

# Task 2: Shipment Tracking
def shipment_tracking():
    while True:
        print("\nShipment Tracking:")
        print("1. Record New Shipment")
        print("2. Update Shipment Status")
        print("3. Back to Main Menu")
        choice = input("Enter your choice: ")

        if choice == '1':
            shipment_id = input("Shipment ID: ")
            supplier_id = input("Supplier ID: ")
            item_id = input("Item ID: ")
            item_name = input("Item Name: ")
            quantity = int(input("Quantity: "))
            shipment_date = input("Shipment Date (YYYY-MM-DD): ")
            delivery_date = input("Delivery Date (YYYY-MM-DD): ")
            status = input("Shipment Status (In Transit/Delivered): ")
            cursor.execute('''
            INSERT OR IGNORE INTO Shipments (ShipmentID, SupplierID, ItemID, ItemName, Quantity, ShipmentDate, DeliveryDate, ShipmentStatus)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            ''', (shipment_id, supplier_id, item_id, item_name, quantity, shipment_date, delivery_date, status))
            conn.commit()
            print("Shipment recorded successfully.")
        elif choice == '2':
            shipment_id = input("Shipment ID: ")
            new_status = input("New Status: ")
            cursor.execute('''
            UPDATE Shipments SET ShipmentStatus = ? WHERE ShipmentID = ?
            ''', (new_status, shipment_id))
            conn.commit()
            print("Shipment status updated successfully.")
        elif choice == '3':
            break
        else:
            print("Invalid choice. Please try again.")

# Task 3: Analyze Supply Chain Data
def analyze_supply_chain_data():
    while True:
        print("\nAnalyze Supply Chain Data:")
        print("1. Report Delayed Shipments")
        print("2. Summarize Shipments by Supplier")
        print("3. Identify Top Suppliers")
        print("4. Back to Main Menu")
        choice = input("Enter your choice: ")

        if choice == '1':
            today = datetime.now().date()
            cursor.execute('''
            SELECT ShipmentID, DeliveryDate FROM Shipments
            WHERE DeliveryDate < ? AND ShipmentStatus != 'Delivered'
            ''', (today,))
            delayed = cursor.fetchall()
            print("Delayed Shipments:")
            for shipment in delayed:
                print(f"Shipment ID: {shipment[0]}, Delivery Date: {shipment[1]}")
        elif choice == '2':
            cursor.execute('''
            SELECT Suppliers.SupplierName, COUNT(Shipments.ShipmentID) as TotalShipments
            FROM Suppliers
            JOIN Shipments ON Suppliers.SupplierID = Shipments.SupplierID
            GROUP BY Suppliers.SupplierName
            ''')
            summary = cursor.fetchall()
            print("Shipments by Supplier:")
            for supplier in summary:
                print(f"Supplier: {supplier[0]}, Total Shipments: {supplier[1]}")
        elif choice == '3':
            cursor.execute('''
            SELECT Suppliers.SupplierName, SUM(Shipments.Quantity) as TotalItems
            FROM Suppliers
            JOIN Shipments ON Suppliers.SupplierID = Shipments.SupplierID
            GROUP BY Suppliers.SupplierName
            ORDER BY TotalItems DESC
            ''')
            top_suppliers = cursor.fetchall()
            print("Top Suppliers:")
            for supplier in top_suppliers:
                print(f"Supplier: {supplier[0]}, Total Items Supplied: {supplier[1]}")
        elif choice == '4':
            break
        else:
            print("Invalid choice. Please try again.")

# Main Menu
def main():
    while True:
        print("\nMain Menu:")
        print("1. Supplier Management")
        print("2. Shipment Tracking")
        print("3. Analyze Supply Chain Data")
        print("4. Exit")
        choice = input("Enter your choice: ")

        if choice == '1':
            supplier_management()
        elif choice == '2':
            shipment_tracking()
        elif choice == '3':
            analyze_supply_chain_data()
        elif choice == '4':
            print("Exiting... Goodbye!")
            break
        else:
            print("Invalid choice. Please try again.")

if __name__ == "__main__":
    main()

# Close the database connection
conn.close()